package com.cqns.demo.dao.mapper;

import com.cqns.demo.dao.entity.BranchInfo;
import java.util.List;

public interface BranchInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_info
     *
     * @mbg.generated Wed Jun 12 12:33:29 CST 2019
     */
    int deleteByPrimaryKey(String branCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_info
     *
     * @mbg.generated Wed Jun 12 12:33:29 CST 2019
     */
    int insert(BranchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_info
     *
     * @mbg.generated Wed Jun 12 12:33:29 CST 2019
     */
    BranchInfo selectByPrimaryKey(String branCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_info
     *
     * @mbg.generated Wed Jun 12 12:33:29 CST 2019
     */
    List<BranchInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch_info
     *
     * @mbg.generated Wed Jun 12 12:33:29 CST 2019
     */
    int updateByPrimaryKey(BranchInfo record);
}