package com.cqns.demo.dao.mapper;

import com.cqns.demo.dao.entity.Dictionary;
import java.util.List;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Mon Jun 03 13:45:51 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Mon Jun 03 13:45:51 CST 2019
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Mon Jun 03 13:45:51 CST 2019
     */
    Dictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Mon Jun 03 13:45:51 CST 2019
     */
    List<Dictionary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Mon Jun 03 13:45:51 CST 2019
     */
    int updateByPrimaryKey(Dictionary record);
}