package com.cqns.demo.dao.mapper;

import com.cqns.demo.dao.entity.Issue;
import java.util.List;

public interface IssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_issue
     *
     * @mbg.generated Wed May 29 15:42:55 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_issue
     *
     * @mbg.generated Wed May 29 15:42:55 CST 2019
     */
    int insert(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_issue
     *
     * @mbg.generated Wed May 29 15:42:55 CST 2019
     */
    Issue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_issue
     *
     * @mbg.generated Wed May 29 15:42:55 CST 2019
     */
    List<Issue> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_issue
     *
     * @mbg.generated Wed May 29 15:42:55 CST 2019
     */
    int updateByPrimaryKey(Issue record);
}