package com.cqns.demo.dao.mapper;

import com.cqns.demo.dao.entity.IssueAttachment;
import java.util.List;

public interface IssueAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_issue_attachment
     *
     * @mbg.generated Wed May 29 17:15:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_issue_attachment
     *
     * @mbg.generated Wed May 29 17:15:16 CST 2019
     */
    int insert(IssueAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_issue_attachment
     *
     * @mbg.generated Wed May 29 17:15:16 CST 2019
     */
    IssueAttachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_issue_attachment
     *
     * @mbg.generated Wed May 29 17:15:16 CST 2019
     */
    List<IssueAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_issue_attachment
     *
     * @mbg.generated Wed May 29 17:15:16 CST 2019
     */
    int updateByPrimaryKey(IssueAttachment record);
}