package com.cqns.demo.dao.mapper;

import com.cqns.demo.dao.entity.RoleResource;
import java.util.List;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Tue May 21 14:36:39 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Tue May 21 14:36:39 CST 2019
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Tue May 21 14:36:39 CST 2019
     */
    RoleResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Tue May 21 14:36:39 CST 2019
     */
    List<RoleResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Tue May 21 14:36:39 CST 2019
     */
    int updateByPrimaryKey(RoleResource record);
}